version: '3'

services:
    # The main application
    website:
        build:
            context: .
            dockerfile: docker/Dockerfile.local
        container_name: wallet-hawk
        environment:
            APP_URL: 'http://localhost'
            DB_HOST: database
            DB_DATABASE: 'wallet_hawk'
            DB_USERNAME: 'root'
            DB_PASSWORD: null
            REDIS_HOST: redis
        ports:
            - '${APP_PORT:-80}:80'
        depends_on:
            - vite
            - database
            # - redis
        networks:
            - laravel
        restart: unless-stopped
        volumes:
            - ".:/var/www"

    # Vite for running development server
    vite:
        image: node:lts-alpine
        command: "yarn run dev -- --host=0.0.0.0"
        working_dir: /app
        restart: unless-stopped
        volumes:
            - '.:/app'
        ports:
            - '5173:5173'
        expose:
            - 5173
        networks:
            - laravel

    # MySQL database for storing application logic
    database:
        image: mariadb:10
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: wallet_hawk
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'database:/var/lib/mysql'
        container_name: hawk-database
        restart: unless-stopped
        networks:
            - laravel
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p" ]
            retries: 3
            timeout: 5s

    # Redis for caching and queue processing
    # redis:
    #     image: 'redis:alpine'
    #     ports:
    #         - '${REDIS_PORT:-6379}:6379'
    #     volumes:
    #         - 'redis:/data'
    #     networks:
    #         - laravel
    #     healthcheck:
    #         test: [ "CMD", "redis-cli", "ping" ]
    #         retries: 3
    #         timeout: 5s

    # phpMyAdmin for database management
    phpmyadmin:
        image: phpmyadmin
        container_name: hawk-phpmyadmin
        restart: always
        depends_on:
            - database
        ports:
            - '${PMA_PORT:-4000}:80'
        environment:
            PMA_HOST: database
            PMA_USER: root
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    database:
    redis:
